### ISSUE TITLE
مشکل راه اندازی روی گیت هاب

### ISSUE THREAD

**Issue by biomanw** [mehdisadeghi/mehdix.ir#2]
سلام 
من سعی کردم با jekyll و کانفیگ های شما روی گیت وبلاگ بالا بیارم اما با این ارور روبرو شدم بعد پوش.
Your site is having problems building: Page build failed. For more information, see https://help.github.com/articles/troubleshooting-github-pages-build-failures. 
رو لوکال بدون مشکل ران میشه ولی وقتی رو گیت مشکل داره

https://github.com/sanlug/sanlugir
sanlug.github.io

**Comment by mehdisadeghi** [comment]
روشی که من شرح دادم فقط وقتی کار می‌کنه که اسم ریپوزیتوریت با اسم وبسایتت یکی نباشه. اسم ریپازیتوری رو عوض کن درست می‌شه.

اگر علاقه‌مندی علتش رو هم بدونی اینه که برخلاف سایر ریپوزیتوری‌ها که یک برنچ برای وبسایت دارند، ریپازیتوری همنام اسم کاربری هر کسی مستقیما از برنج مستر توسط گیت‌هاب لود و بیلد می‌شه. اگر دقت کنی می‌بینی که اسم ریپازیتوری من هم با یوزرنیم من فرق می‌کنه.

**Comment by biomanw** [comment]
خب این مشکل رو مرتفع کردم الان سایت بالا میاد ولی باید بصورت لوکال سایت رو build کنم
و بعد فایل ها رو پوش کنم رو گیت.
خود گیت هاب قابلیت این رو نداره که سایت رو از روی فایل ها بیلد کنه
بنظرت برای این نیست که از پلاگین غیر استاندارد استفاده شده؟
چطور پلاگین رو میشه حذف کرد ؟

**Comment by biomanw** [comment]
میشه تو تلگرام باهات در ارتباط باشم؟
hamidtgj

**Comment by mehdisadeghi** [comment]
من نحوه راه‌اندازی رو در وبسایتم شرح دادم. لطفا مقاله‌های مرتبط رو بخونید مشکلتون رفع می‌شه. مثلا در این یکی نحوه بیلد رو شرح دادم:
http://mehdix.ir/wercker-intro.html

لطفا اگر مشکلی بود همینجا بنویسید. چون مشکل شما مشکل دیگری هم می‌تونه باشه.
